---
title: "step1_data_prepare"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,message = F,warning = F)
```

# 1. TCGA
## 1.1 TCGA expression matrix
```{r}
exp_gbm = read.table("TCGA-GBM.htseq_fpkm.tsv.gz",
                     header = T,row.names = 1,check.names = F)
exp_lgg = read.table("TCGA-LGG.htseq_fpkm.tsv.gz",
                     header = T,row.names = 1,check.names = F)
exp1 = as.matrix(cbind(exp_gbm,exp_lgg))

# ensembl to gene symbol
library(stringr)
library(AnnoProbe)
rownames(exp1) = str_split(rownames(exp1),"\\.",simplify = T)[,1];head(rownames(exp1))
re = annoGene(rownames(exp1),ID_type = "ENSEMBL");head(re)
library(tinyarray)
exp1 = trans_array(exp1,ids = re,from = "ENSEMBL",to = "SYMBOL")
exp1[1:4,1:4]
dim(exp1)

# Keep tumor sample only
Group = make_tcga_group(exp1)
table(Group)
exp1 = exp1[,Group == "tumor"]

# Keep genes expressed more than 200 samples
exp1 = exp1[apply(exp1, 1, function(x){sum(x>0)>200}),]
```

## 1.2 TCGA clinical information
```{r}
surv_gbm = readr::read_tsv("TCGA-GBM.survival.tsv")
surv_gbm$TYPE = "GBM"
surv_lgg = readr::read_tsv("TCGA-LGG.survival.tsv")
surv_lgg$TYPE = "LGG"
surv1 = rbind(surv_gbm,surv_lgg)
head(surv1)
table(colnames(exp1) %in% surv1$sample)
s = intersect(colnames(exp1),surv1$sample)
exp1 = exp1[,s]
surv1 = surv1[match(s,surv1$sample),]
colnames(surv1)[c(2,4)] = c("event","time")
exp1[1:4,1:4]
head(surv1)
identical(colnames(exp1),surv1$sample)
```
 
# 2.CGGA_array
```{r}
exp2 = read.table("CGGA/CGGA.mRNA_array_301_gene_level.20200506.txt",header = T,row.names = 1)
surv2 = read.table("CGGA/CGGA.mRNA_array_301_clinical.20200506.txt",sep = "\t",header = T,check.names = F)
head(surv2)
s = intersect(surv2$CGGA_ID,colnames(exp2))
exp2 = as.matrix(exp2[,s])
surv2 = surv2[match(s,surv2$CGGA_ID),]
colnames(surv2)[c(9,8)] = c("event","time")
exp2[1:4,1:4]
head(surv2)
identical(surv2$CGGA_ID,colnames(exp2))
```

## 3.CGGA
```{r}
exp3 = read.table("CGGA/CGGA.mRNAseq_325.RSEM-genes.20200506.txt",header = T,row.names = 1)
exp3 = as.matrix(log2(exp3+1))
surv3 = read.table("CGGA/CGGA.mRNAseq_325_clinical.20200506.txt",sep = "\t",header = T,check.names = F)
head(surv3)
colnames(surv3)[c(8,7)] = c("event","time")

s = intersect(surv3$CGGA_ID,colnames(exp3))
exp3 = exp3[,s]
surv3 = surv3[match(s,surv3$CGGA_ID),]
exp3[1:4,1:4]
head(surv3)
identical(surv3$CGGA_ID,colnames(exp3))
```

# 4.GSE16011
## 4.1 GSE16011 expression matrix
```{r}
library(tinyarray)
geo = geo_download("GSE16011")
library(stringr)

# Keep tumor samples
k = str_detect(geo$pd$title,"glioma");table(k)

geo$exp = geo$exp[,k]
geo$pd = geo$pd[k,]

# ensembl to gene symbol
gpl = GEOquery::getGEO(filename = "GPL8542_family.soft.gz",destdir = ".")

ids  = gpl@dataTable@table[,1:2]
library(clusterProfiler)
library(org.Hs.eg.db)
e2s = bitr(ids$ORF,fromType = "ENTREZID",toType = "SYMBOL",OrgDb = "org.Hs.eg.db")
ids = merge(ids,e2s,by.x = "ORF",by.y = "ENTREZID")
ids = ids[,2:3]
colnames(ids) = c("probe_id","symbol")
exp4 = trans_array(geo$exp,ids)
surv4 = geo$pd[,c(1,4,7,9)]
exp4[1:4,1:4]
head(surv4)
identical(rownames(surv4),colnames(exp4))
```

## 4.1 GSE16011 clinical information

https://aacrjournals.org/cancerres/article/69/23/9065/553005/Intrinsic-Gene-Expression-Profiles-of-Gliomas-Are

```{r}
if(!file.exists("exp_surv4.Rdata")){
  library(tabulizer)
  f <- "00085472can092307-sup-stabs_1-6.pdf"
  re <- extract_tables(f,pages = 1:10)
  str(re)
  re = do.call(rbind,re)
  re[1:4,1:4]
  colnames(re) = re[1,]
  re = re[-1,]
  re = data.frame(re)
  re[re==""]=NA
  
  library(readr)
  re$Survival..years. = parse_double(re$Survival..years.,locale = locale(decimal_mark = ","))
  
  re$Age.at.diagnosis = parse_double(re$Age.at.diagnosis,locale = locale(decimal_mark = ","))
  
  dim(exp4)
  k = re$Reviewed.histological.diagnosis!="control";table(k)
  re = re[k,]
  re$Database.number = paste("glioma",re$Database.number)
  surv4$ID = rownames(surv4)
  
  surv4 = merge(surv4,re,by.x = "title",by.y = "Database.number")
  colnames(surv4)[13:14] = c("event","time")
  table(surv4$event)
  surv4$time = as.integer(surv4$time*365) 
  surv4$event[surv4$event=="Lost to\rfollow up"]=NA
  table(surv4$event)
  
  surv4$event=ifelse(surv4$event=="Alive",0,1)
  head(surv4)
  
  s = intersect(surv4$ID,colnames(exp4))
  exp4 = exp4[,s]
  surv4 = surv4[match(s,surv4$ID),]
  save(exp4,surv4,file = "exp_surv4.Rdata")
}
load("exp_surv4.Rdata")
exp4[1:4,1:4]
head(surv4)
identical(surv4$ID,colnames(exp4))
```

# Save datasets
```{r}
par(mfrow = c(2,2))
boxplot(exp1[,1:10])
boxplot(exp2[,1:10])
boxplot(exp3[,1:10])
boxplot(exp4[,1:10])
save(exp1,surv1,file = "exp_surv1.Rdata")
save(exp2,surv2,file = "exp_surv2.Rdata")
save(exp3,surv3,file = "exp_surv3.Rdata")
save(exp4,surv4,file = "exp_surv4.Rdata")
```
