---
title: "Immnue"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,message = F,warning = F)
```

### 1.TIP genes

http://biocc.hrbmu.edu.cn/TIP/index.jsp

```{r fig.height=13,fig.width=13}
rm(list = ls())
library(tinyarray)
tip = read.delim("TIP_genes.txt",header = T)
nrow(tip)
head(tip)
gs = tip$GeneSymbol[tip$Direction =="negative"];length(gs)
load("../1_data_pre/exp_surv1.Rdata")
load("../1_data_pre/exp_surv2.Rdata")
load("../1_data_pre/exp_surv3.Rdata")
load("../1_data_pre/exp_surv4.Rdata")
load("../2_model/model_genes_survs.Rdata")

exps = list(exp1,exp2,exp3,exp4)

#i = 1
p1 = list()
corhorts = c("TCGA","CGGA_array","CGGA","GSE16011")
for(i in 1:4){
  n = exps[[i]][rownames(exps[[i]])%in% gs,]
  n = n[,order(survs[[i]]$fp)]
  g = sort(survs[[i]]$Risk)
  rn = apply(n,1,function(x){
    #x = n[1,]
    p = wilcox.test(x~g)$p.value
    j = ifelse(p<=0.001,
           "***",
           ifelse(p<=0.01,
                  "**",
                  ifelse(p<=0.05,"*","")))
    return(j)
  })
  rownames(n) = paste0(rownames(n),rn)
  p1[[i]] =draw_heatmap(n,g,cluster_cols = F,main = corhorts[[i]],show_rownames = T)
}
library(patchwork)
pdf("tip.pdf",width = 8,height = 10)
wrap_plots(p1)
dev.off()
```

#### boxplot

```{r}
g4 = c("VEGFA","TGFB1","CD95L","FGL2","IL10")
p2 = list()
library(ggplot2)
for(i in 1:4){
  p2[[i]] = draw_boxplot(exps[[i]][rownames(exps[[i]])%in% g4,],survs[[i]]$Risk,sort = F)+
    ggtitle(corhorts[[i]])+
    theme(plot.title = element_text(hjust = 0.5)) 
}
library(ggplot2)
wrap_plots(p2) + plot_layout(guides = "collect") &
  theme(legend.position='right')
```

### 2.immune cell ratio

mmc3.xlsx from TableS6:https://www.sciencedirect.com/science/article/pii/S2211124716317090

```{r fig.height= 10,fig.width=15}
geneset = rio::import("mmc3.xlsx",skip = 2)
geneset = split(geneset$Metagene,geneset$`Cell type`)
lapply(geneset[1:3], head)
library(GSVA)
f = "ssgsea_result.Rdata"
if(!file.exists(f)){
  p = list()
for(i in 1:4){
  #i = 1
  re <- gsva(exps[[i]], geneset, method="ssgsea",
               mx.diff=FALSE, verbose=FALSE
)
  p[[i]] = draw_boxplot(re,survs[[i]]$Risk)+
    ggtitle(corhorts[[i]])+
    theme(plot.title = element_text(hjust = 0.5))+ 
    theme(plot.margin=unit(c(1,3,1,1),'lines')) #调整边距
}
  save(re,p,file = f)
}
load(f)

wrap_plots(p)+ plot_layout(guides = "collect") &
  theme(legend.position='right')
```

### Immune subtype

```{r}
#devtools::install_github("Gibbsdavidl/ImmuneSubtypeClassifier")
library(ImmuneSubtypeClassifier)

f = "immu_res.Rdata"
if(!file.exists(f)){
  res = list()
for(i in 1:4){
  a <- callEnsemble(X = exps[[i]], geneids = 'symbol')[,1:2]
  a$corhort = corhorts[[i]]
  a$Risk = survs[[i]]$Risk
  res[[i]] = a
}
  save(res,file = f)
}
load(f)
```

```{r fig.width= 8}
res2 = do.call(rbind,res)
head(res2)
res2$BestCall = factor(paste0("C",res2$BestCall))

library(dplyr)
dat2 <- res2 %>%
 group_by(corhort,Risk, BestCall) %>% 
 summarise(count = n())

library(paletteer)
pb = ggplot() + geom_bar(data =dat2, aes(x = Risk, y = count, fill = BestCall),
 stat = "identity",
 position = "fill")+
  theme_classic()+
  scale_fill_paletteer_d("RColorBrewer::Set2")+
  labs(x = "Risk",y = "Percentage")+
  facet_wrap(~corhort,nrow = 1)
pb
```

### ICGs

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7786136/

```{r fig.height= 10,fig.width=12}

tmp = readLines("immune_checkpoint.txt")
genes = str_split(tmp,", ")[[1]]
sapply(exps, function(x){genes[!(genes %in% rownames(x))]})
pi = list()

for(i in 1:4){
  n = exps[[i]][rownames(exps[[i]])%in% genes,]
  n = n[,order(survs[[i]]$fp)]
  g = sort(survs[[i]]$Risk)
  rn = apply(n,1,function(x){
    #x = n[1,]
    p = wilcox.test(x~g)$p.value
    j = ifelse(p<=0.001,
           "***",
           ifelse(p<=0.01,
                  "**",
                  ifelse(p<=0.05,"*","")))
    return(j)
  })
  rownames(n) = paste0(rownames(n),rn)
  pi[[i]] =draw_heatmap(n,g,cluster_cols = F,main = corhorts[[i]],show_rownames = T)
}
library(patchwork)
wrap_plots(pi)
```

### Correlation

```{r fig.height= 10,fig.width= 16}
#i = 1
library(ggpubr)
pc = list()
for(i in 1:4){
  dat = data.frame(PDCD1 = exps[[i]]["PDCD1",],
                  CD274 = exps[[i]]["CD274",],
                  risk_score = survs[[i]]$fp,
                  Risk = survs[[i]]$Risk)

  p1 = ggscatter( dat, 
             y = "PDCD1", x = "risk_score",
             xlab = "Risk score",
             size =1,color = "#1d4a9d",
             add = "reg.line", 
            add.params = list(color = "red"))+
    stat_cor(label.y = 5)
  p2 = ggscatter( dat, 
             y = "CD274", x = "risk_score",
             xlab = "Risk score",
             size =1,color = "#1d4a9d",
             add = "reg.line", 
            add.params = list(color = "red"),
            title = corhorts[[i]])+
    stat_cor(label.y = 5)
  p3 = draw_boxplot(t(dat[,1:2]),dat$Risk)
  pc[[i]] = list(p1,p2,p3)
}
wrap_plots(c(pc[[1]],pc[[3]],pc[[2]],pc[[4]]),nrow = 2)
```
